### ISSUE TITLE
各种操作前提示

### ISSUE THREAD

**Issue by syzlztt** [LightingSalt/PPHead#124]
整理了一下弹confirm框的情况

eventDetail
点击拒绝，alert confirm框 确定拒绝该活动吗
点击退出，alert confirm框 确定退出该活动吗
点击解散，alert confirm框 title="解散活动确认", 内容="活动解散后将不可恢复，并通知所有报名者\n您确认要继续吗"

确认活动
点击踢人，alert confirm框 你确定要移除该成员吗

活动成员列表
点击踢人，alert confirm框 你确定要移除该成员吗

创建/管理活动高级
点击语音的删除，alert confirm框 确定删除该语音吗

第三方账号绑定
点击绑定，如果已被绑，alert confirm框 该第三方账号已被绑定\n如果继续将会与其他账号解绑

**Comment by hsj1606** [comment]
退出活动，拒绝活动没有alert

**Comment by hsj1606** [comment]
验证通过
