### ISSUE TITLE
threePartLogin改动

### ISSUE THREAD

**Issue by hsj1606** [LightingSalt/PPHead#138]
如果SourceTypeEnum=WEB，我把accessToken给你（参数为verifyToken），你去拿openId（getQqOpenId），如果openId未注册，则去获取QQ头像昵称（getQqUserInfo），再进行注册。最后返回userBean

public String getQqOpenId(String accessToken) throws Exception {
		String getOpenIdUrl = "https://graph.qq.com/oauth2.0/me?access_token=" + accessToken;
		String getOpenIdResponse = HttpUtil.sendGetRequest(getOpenIdUrl, null);
		log.info("qq getOpenIdResponse=" + getOpenIdResponse);
		String openId = JSON.parseObject(getOpenIdResponse.replace("callback( ", "").replace(" );", "")).getString("openid");
		log.info("qq openId=" + openId);
		return openId;
	}

	public JSONObject getQqUserInfo(String openId, String accessToken) throws Exception {
		String getUserInfoUrl = "https://graph.qq.com/user/get_user_info?access_token=" + accessToken + "&oauth_consumer_key=" + PropConstants.getProperties("qq_app_id") + "&openid=" + openId;
		String getUserInfoResponse = HttpUtil.sendGetRequest(getUserInfoUrl, null);
		log.info("qq getUserInfoResponse=" + getUserInfoResponse);
		JSONObject userInfoJsonObj = JSON.parseObject(getUserInfoResponse);
		String imgUrl = userInfoJsonObj.getString("figureurl_qq_1"); 头像
		String nickname = userInfoJsonObj.getString("nickname"); 昵称
		return userInfoJsonObj;
	}

**Comment by bryan31** [comment]
done
