### ISSUE TITLE
IOS-创建/管理活动增加时间快捷选项

### ISSUE THREAD

**Issue by hsj1606** [LightingSalt/PPHead#154]
![ijpo_l_7 2cd167cy6gq c](https://cloud.githubusercontent.com/assets/12151317/10787833/798f53c2-7dae-11e5-811b-321a53a43234.png)

增加年份的前后切换
增加快捷选项
周一到周三：显示明天/本周五/本周六/本周日
周四：显示明天/本周六/本周日
周五：显示明天/本周日
周六/周日：显示明天/下周五/下周六/下周日

**Comment by hsj1606** [comment]
没有年份左右切换，本周5/6/日点击后日期显示不对

![f4e01366b930d6f2bd9a83840e5f8201](https://cloud.githubusercontent.com/assets/12151317/11037075/eadd9fa2-8736-11e5-917a-3e9feff01da4.png)

**Comment by syzlztt** [comment]
左右箭头图

**Comment by agoodmonkey** [comment]
用button，圆角和明天、下周五几个一样，按钮label打字左右箭头（就是现在的）
