### ISSUE TITLE
ios-界面排版-提示框

### ISSUE THREAD

**Issue by agoodmonkey** [LightingSalt/PPHead#222]
样式参考效果图

**Comment by hsj1606** [comment]
![5 0 ebj8ee10rxw ez11zp](https://cloud.githubusercontent.com/assets/12151317/10899971/3fe85c16-8215-11e5-9d6d-69813d09ea35.png)

**Comment by hsj1606** [comment]
![b57 hmyk6 01cx26444t 1n](https://cloud.githubusercontent.com/assets/12151317/10900001/92d65f18-8215-11e5-8a91-ffb0d6c3fd5b.png)

**Comment by hsj1606** [comment]
带标题和文字的
![gafu2d5 igbfl dngr6](https://cloud.githubusercontent.com/assets/12151317/10900061/2e778d98-8216-11e5-9961-46906d924494.png)

**Comment by hsj1606** [comment]
编辑好友备注
![hjh wq8jlrq u _ i jgi](https://cloud.githubusercontent.com/assets/12151317/10900107/abb1974a-8216-11e5-95bd-43c31d2e9527.jpg)

**Comment by hsj1606** [comment]
发送好友请求
![n9b60md 9gb7 nms7 x y6](https://cloud.githubusercontent.com/assets/12151317/10900123/e5810190-8216-11e5-97d0-693ad7f5ed1b.png)

**Comment by hsj1606** [comment]
confirm框确认应该在右边，取消在左边
