### ISSUE TITLE
ios-界面排版-活动详情成员列表样式不对

### ISSUE THREAD

**Issue by hsj1606** [LightingSalt/PPHead#225]
参考如下
![zxoes cdh30rg5 ps2 lj4](https://cloud.githubusercontent.com/assets/12151317/10900157/6db41660-8217-11e5-97a6-1dae1821b6e7.png)

**Comment by agoodmonkey** [comment]
1.大小不对，一行三个，参考效果图
2.底色可以用当前白底
3.发起人三个字要能挡住底线
