### ISSUE TITLE
公众号-缺欢迎信息，碰头菜单没广告

### ISSUE THREAD

**Issue by hsj1606** [LightingSalt/PPHead#244]

**Comment by hsj1606** [comment]
![jf uopx8jl9d 2gxa5wch](https://cloud.githubusercontent.com/assets/12151317/10998464/407008d8-84d0-11e5-9da3-f9ba5699f67c.jpg)

**Comment by bryan31** [comment]
done

**Comment by hsj1606** [comment]
碰头菜单没广告

**Comment by bryan31** [comment]
done
