### ISSUE TITLE
IOS-界面排版-设置页对齐

### ISSUE THREAD

**Issue by hsj1606** [LightingSalt/PPHead#248]
![4m3yk2vslzg a c9mo3ogty](https://cloud.githubusercontent.com/assets/12151317/11036969/4c8ada40-8736-11e5-9dae-7945a2430054.png)

红框部分应与箭头对齐

**Comment by hsj1606** [comment]
SORRY,描述不准确，碰头账号应和手机号对齐
![kurxhsw916d_c _1u 3o](https://cloud.githubusercontent.com/assets/12151317/11166840/98ddc604-8b83-11e5-9213-d66d14bf9867.png)

**Comment by agoodmonkey** [comment]
还有字体大小太小，请参考效果图或者调整时候在线问我
