### ISSUE TITLE
IOS-首页过滤条件加上

### ISSUE THREAD

**Issue by agoodmonkey** [LightingSalt/PPHead#270]
见效果图。
1.默认在索引图片和列表中间
2.滑动到顶部后锁定在顶部

**Comment by hsj1606** [comment]
![fag5e 1c0 3 dv_ jowbq j](https://cloud.githubusercontent.com/assets/12151317/11655489/27e6fa42-9de9-11e5-9882-11858804635a.jpg)
位置反了，全部活动应该在上面

**Comment by hsj1606** [comment]
当活动列表较长时，一直往下滚后置顶消失
![qq 20151209105551](https://cloud.githubusercontent.com/assets/12151317/11675287/6181bde4-9e63-11e5-937b-33c690e5fc75.png)
![qq 20151209105556](https://cloud.githubusercontent.com/assets/12151317/11675286/617e3872-9e63-11e5-8157-519e9376b959.png)
