### ISSUE TITLE
IOS-我的-钱包

### ISSUE THREAD

**Issue by agoodmonkey** [LightingSalt/PPHead#274]
1。支持支付宝和微信
2。充值（10，20，50，100，200，500）
3。买卡（点击卡片列表的卡，增加购买按钮，确认后扣款，余额不足跳到充值，充值成功后跳到待支付）
4。查看交易记录

界面会尽快给效果图

**Comment by syzlztt** [comment]
iOS平台虚拟货币不能通过第三方平台购买，只能通过内购。

11.2Apps utilizing a system other than the In-App Purchase API (IAP) to purchase content, functionality, or services in an App will be rejected11.3Apps using IAP to purchase physical goods or goods and services used outside of the application will be rejected11.4Apps that use IAP to purchase credits or other currencies must consume those credits within the application

11.2 说在 App 内使用非 IAP 的第三方支付购买内容或服务、解锁功能是不允许的；11.3 说用 IAP 购买实物或者应用外的货物或服务是不允许的；11.3 说通过 IAP 购买的货币必须只在 App 内使用。

具体原因类似这个 http://www.zhihu.com/question/20665809/answer/15788162
