### ISSUE TITLE
IOS-增加卡片购买点击事件

### ISSUE THREAD

**Issue by agoodmonkey** [LightingSalt/PPHead#283]
参考Android

1.在我-卡片-点击某个查看卡片详情-点击底部购买按钮（没有库存时候）
PAGE_PAY_ClickBuyBtnFromCardDetail	页面_支付_点击购买按钮_卡片详情里(带参)

2.在新建活动-点击选卡标签-中间购买按钮（没有库存时候）
PAGE_PAY_ClickBuyBtnFromNewEvent	页面_支付_点击购买按钮_新建活动里(带参)

**Comment by hsj1606** [comment]
不是点击支付弹窗的购买
是点击1. 卡片预览弹窗底部购买按钮 2. 创建活动弹窗“立即购买”按钮
