### ISSUE TITLE
IOS-卡片购买历史

### ISSUE THREAD

**Issue by agoodmonkey** [LightingSalt/PPHead#291]
参考Android

在卡片的工具栏，当前使用历史的左侧增加一个按钮“购买历史”，点击后列出
卡片缩略图   卡片名字                          数量：3
暂用两行       购买时间:2015-01-01      总价：￥3.00

上下拉分页 一页20条

**Comment by hsj1606** [comment]
![h2h4 wqfn4 weg_k1n7plnp](https://cloud.githubusercontent.com/assets/12151317/11622810/57d341a2-9d03-11e5-8576-713e6b686230.png)
