### ISSUE TITLE
IOS-个人中心增加栏目如效果图

### ISSUE THREAD

**Issue by agoodmonkey** [LightingSalt/PPHead#301]
上次发版没来得及做完的加上，参考Android
![image](https://cloud.githubusercontent.com/assets/6252876/11325125/cafa44d4-9180-11e5-8eef-417a32675e2f.png)

关于碰头
我来评分
我来提意见（改为1对1客服）
清除缓存
检查更新（IOS不能做则不做）

**Comment by hsj1606** [comment]
1对1客服，关于碰头不做，评分点了是跳到AppStore的评分，参考其他app
