### ISSUE TITLE
确认哪些地方要友盟统计

### ISSUE THREAD

**Issue by hsj1606** [LightingSalt/PPHead#41]

**Comment by agoodmonkey** [comment]
PAGE_Event_ClickAddBtn,页面_活动_点击创建按钮,0
PAGE_Event_ClickAddByCard,页面_活动_点击通过卡片创建(带参),0
PAGE_Event_ClickCardTheme,页面_活动_点击所选卡片(带参),0
PAGE_Event_ClickQuickTime,页面_活动_点击快捷时间按钮(带参),0
PAGE_Event_ClickSaveSettingText,页面_活动_点击保存文字介绍,0
PAGE_Event_ClickSaveSettingAudio,页面_活动_点击保存语音介绍,0
PAGE_Event_ClickSettingPayment,页面_活动_点击费用设置(带参),0
PAGE_Event_ClickSettingTimeMutiple,页面_活动_点击时间多选设置(带参),0
PAGE_Event_ClickSettingLocationMutiple,页面_活动_点击地址多选设置(带参),0
PAGE_Event_SelectSettingTimeCustom,页面_活动_选中可多选时间,0
PAGE_Event_SelectSettingLocationCustom,页面_活动_选中可多选地点,0
PAGE_Event_ClickEditBtn,页面_活动_点击编辑按钮,0
PAGE_Event_ClickCardIndex,页面_活动_点击索引卡片(带参),0
PAGE_Event_ClickCardList,页面_活动_点击卡片列表(带参),0
PAGE_Event_ClickEventJoinBtn,页面_活动_点击报名按钮,0
PAGE_Event_ClickEventRefuseBtn,页面_活动_点击拒绝按钮,0
PAGE_Event_ClickEventQuitBtn,页面_活动_点击退出按钮,0
PAGE_Event_ClickEventConfirmBtn,页面_活动_点击确定活动按钮,0
PAGE_Event_ClickEventShareToolBtn,页面_活动_点击分享工具按钮,0
PAGE_Event_ClickEventCancelBtn,页面_活动_点击解散按钮,0
PAGE_Event_ClickEventSignInBtn,页面_活动_点击碰头按钮,0
PAGE_Event_ClickEventLotteryBtn,页面_活动_点击抽奖按钮,0
PAGE_Event_ClickEventLotteryUserListBtn,页面_活动_点击查看抽奖名单按钮,0
PAGE_Event_ClickEventTextIntroBtn,页面_活动_点击查看文字介绍按钮,0
PAGE_Event_ClickEventAudioIntroBtn,页面_活动_点击查看音频介绍按钮,0
PAGE_Event_ClickEventNewTimeBtn,页面_活动_点击添加新时间按钮,0
PAGE_Event_ClickEventNewLocationBtn,页面_活动_点击添加新地点按钮,0
PAGE_Event_ClickEventUserListBtn,页面_活动_点击查看用户列表按钮,0
PAGE_Event_LoadEventDetail,页面_活动_载入详情页面,0
PAGE_Event_ClickEventShareToChannelBtn,页面_活动_点击分享到某渠道按钮(带参),0

PAGE_Friend_ClickAddBtn,页面_好友_点击添加好友按钮,0
PAGE_Friend_ClickSendAddRequestBtn,页面_好友_点击请求加好友按钮,0
PAGE_Friend_LoadFriendDetail,页面_好友_载入好友详情页面,0
PAGE_Friend_ClickEditFriendSortBtn,页面_好友_点击好友分类按钮(带参),0
PAGE_Friend_ClickSaveFriendMemoBtn,页面_好友_点击好友备注按钮,0

PAGE_UserCenter_ClickCardMenuBtn,页面_个人中心_点击卡片菜单,0
PAGE_UserCenter_ClickPhotoMenuBtn,页面_个人中心_点击相册菜单,0
PAGE_UserCenter_ClickSettingMenuBtn,页面_个人中心_点击设置菜单,0
PAGE_UserCenter_ClickEditNicknameBtn,页面_个人中心_点击修改昵称按钮,0
PAGE_UserCenter_ClickEditUserCoverBtn,页面_个人中心_点击修改封面按钮,0
PAGE_UserCenter_ClickSaveMobileBtn,页面_个人中心_点击保存绑定手机号按钮,0
PAGE_UserCenter_ClickSaveEmailBtn,页面_个人中心_点击保存绑定邮箱按钮,0
PAGE_UserCenter_ClickSaveThirdPartyBtn,页面_个人中心_点击保存第三方账号按钮(带参),0
PAGE_UserCenter_ClickSaveGenderBtn,页面_个人中心_点击保存生日(带参),0
PAGE_UserCenter_ClickSaveBirthdayBtn,页面_个人中心_点击保存生日按钮,0
PAGE_UserCenter_ClickDownloadBtn,页面_个人中心_点击下载安装包按钮(带参),0

PAGE_UserAuth_ClickAccountTypeBtn,页面_账户认证_点击账户类型(带参),0
PAGE_UserAuth_ClickResendCheckCodeBtn,页面_账户认证_点击重发验证码(带参),0
PAGE_UserAuth_ClickRegBtn,页面_账户认证_点击注册按钮,0
PAGE_UserAuth_ClickRandomNicknameBtn,页面_账户认证_点击换一换按钮,0

**Comment by agoodmonkey** [comment]
注意：
1）ClickSave是点击保存的按钮才统计，例如绑定手机号，不是点菜单统计，是最终确认的保存按钮才统计
2）Select是选中状态才统计
3）Load是页面载入就统计
