### ISSUE TITLE
活动参与者列表&成员列表页创建者特殊化标注

### ISSUE THREAD

**Issue by bryan31** [LightingSalt/PPHead#46]
加个边框或者角标，表明是创建者。

**Comment by agoodmonkey** [comment]
参考android最新版，发起人增加文字标示，红底白字

**Comment by agoodmonkey** [comment]
![d3 3 g6 jvh0yp8cd8 u](https://cloud.githubusercontent.com/assets/6252876/10862667/bfe64b4c-7fec-11e5-9d1a-e20c25581bc7.png)
